### PR TITLE
Fixes jetty tasks so you can run them from the root of your working directory

### PR DESCRIPTION
**Pull request by flyingzumwalt**

### CODE REVIEW

**Comment by jcoyne** [comment]
This will also import `solr:reindex`, which I suspect will fail if you run it. Perhaps split the jetty stuff into its own rake file?

**Comment by flyingzumwalt** [comment]
The alternative is not being able to run the tests.  We should merge this and then you can submit a PR that moves the reindex task.

**Comment by jcoyne** [comment]
It's easier to do it right the first time than to have to find and then go back and fix bugs.

**Comment by flyingzumwalt** [comment]
Closing the PR and replacing it with a ticket #69.  Keep the branch for reference (for now).

**Comment by jpstroop** [comment]
:+1:

**Pull request closed without merging**
