### PR TITLE
Cleaning before each example is slow, stop doing this.

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by tpendragon** [comment]
According to https://travis-ci.org/projecthydra-labs/curation_concerns/pull_requests it doesn't seem like this gained us much

**Comment by jcoyne** [comment]
It is true that we aren't seeing much in the way of speed improvements (most of the time on travis is spent running generators), however, this exercise did surface a few bugs.  I wonder if it isn't better this way, where you are explicit about each test that requires a clean repo.

**Comment by tpendragon** [comment]
It seems strange to have to explicitly clean out your environment per test.

**Comment by tpendragon** [comment]
I'm pretty :-1: on this one, can someone else from @projecthydra/sufia-code-reviewers comment?

**Comment by mjgiarlo** [comment]
I'm +0 on this one. It'd be good for @tpendragon to be sold on it (and for this to be rebased).

**Pull request closed without merging**
