### PR TITLE
Remove Collection#remove_self_from_members

### PR DESCRIPTION
**Pull request by jcoyne**
this is now handled by the ancestor checker in Hydra-PCDM
Also updated all the underlying dependencies.

### CODE REVIEW

**Comment by jcoyne** [comment]
This test is failing because the GenericWork is no longer saving the head_id of the proxy list: 
https://travis-ci.org/projecthydra-labs/curation_concerns/builds/71827173#L2151

**Comment by jpstroop** [comment]
projecthydra-labs/hydra-works#158 is blocking

**Comment by jcoyne** [comment]
projecthydra-labs/hydra-works#159 is also blocking

**Comment by jpstroop** [comment]
Ah! Was trying to figure out where that was coming from.

**Comment by jpstroop** [comment]
I merged projecthydra-labs/hydra-works#159, but would feel more comfortable if someone closer to Hydra::Works would review projecthydra-labs/hydra-works#158

**Pull request merged**
