### PR TITLE
removes all notion of Batches (moving it back into sufia-core) ref pr…

### PR DESCRIPTION
**Pull request by flyingzumwalt**
removes all notion of Batches (moving it back into sufia-core) ref projecthydra-labs/sufia-core#7

also fixes a bug in _representative_media.html.erb

blocks projecthydra-labs/sufia-core#7

### CODE REVIEW

**Comment by flyingzumwalt** [comment]
This has one test that fails on travis but not locally.  I'm not sure why.

**Comment by flyingzumwalt** [comment]
@mjgiarlo please check this in the morning.  I can't recreate the failure locally.
```
rspec spec/features/create_work_spec.rb 
```

**Comment by mjgiarlo** [comment]
Works for me locally, @flyingzumwalt.

**Comment by flyingzumwalt** [comment]
Fixed it! @mjgiarlo please review & merge , which will let us update projecthydra-labs/sufia-core#7 to point to curation_concerns master and merge that

**Comment by mjgiarlo** [comment]
:+1:

**Pull request merged**
