### PR TITLE
Use Latest Hydra-Works

### PR DESCRIPTION
**Pull request by tpendragon**

### CODE REVIEW

**Comment by tpendragon** [comment]
I...don't know what's going on here.

**Comment by jcoyne** [comment]
I'm seeing this:
```
   Ldp::HttpError:
       STATUS: 500 java.util.NoSuchElementException
       	at com.google.common.collect.Iterators$1.next(Iterators.java:80)
       	at org.fcrepo.kernel.modeshape.rdf.impl.mappings.PropertyValueIterator.computeNext(PropertyValueIterator.java:68)
       	at org.fcrepo.kernel.modeshape.rdf.impl.mappings.PropertyValueIterator.computeNext(PropertyValueIterator.java:35)
       	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
       	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
       	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
       	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:650)
       	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
       	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
       	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
       	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:547)
       	at com...
     # /Users/justin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ldp-0.5.0/lib/ldp/client/methods.rb:119:in `block in check_for_errors'
     # /Users/justin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ldp-0.5.0/lib/ldp/client/methods.rb:117:in `tap'
     # /Users/justin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ldp-0.5.0/lib/ldp/client/methods.rb:117:in `check_for_errors'
     # /Users/justin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ldp-0.5.0/lib/ldp/client/methods.rb:53:in `block in get'
     # /Users/justin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
     # /Users/justin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ldp-0.5.0/lib/ldp/client/methods.rb:33:in `get'
     # /Users/justin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-9.10.1/lib/active_fedora/caching_connection.rb:13:in `get'
     # /Users/justin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ldp-0.5.0/lib/ldp/resource.rb:54:in `get'
     # /Users/justin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ldp-0.5.0/lib/ldp/resource/rdf_source.rb:50:in `response_graph'
     # /Users/justin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ldp-0.5.0/lib/ldp/resource/rdf_source.rb:31:in `graph'
     # /Users/justin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-9.10.1/lib/active_fedora/file/attributes.rb:17:in `digest'
```

**Comment by tpendragon** [comment]
@jcoyne @escowles Any thoughts on why this would suddenly be broken? I'm pretty sure we've been running this test on 4.5 for a while

**Comment by escowles** [comment]
I don't know what changed, but this definitely looks like a F4 bug.  I'll dig into it on Monday to figure out what that's about.

**Comment by jcoyne** [comment]
I think this is caused by sending:

```
IngestFileJob.perform_later(file_set_id, working_file, mime_type, user.user_key, relation)
```

when the `mime_type` is nil.

**Comment by jcoyne** [comment]
Uh, nope, that wasn't it. :disappointed:

**Comment by jcoyne** [comment]
New theory: It's attempting to update the metadata node by patching this SPARQL

```
DELETE { <http://127.0.0.1:8986/rest/test/4b/29/b6/01/4b29b601h/files/37b8c774-c4de-4257-abad-e454c74afd44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?change . }
  WHERE { <http://127.0.0.1:8986/rest/test/4b/29/b6/01/4b29b601h/files/37b8c774-c4de-4257-abad-e454c74afd44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?change . } ;
INSERT {
<http://127.0.0.1:8986/rest/test/4b/29/b6/01/4b29b601h/files/37b8c774-c4de-4257-abad-e454c74afd44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/ldp#NonRDFSource> .
<http://127.0.0.1:8986/rest/test/4b/29/b6/01/4b29b601h/files/37b8c774-c4de-4257-abad-e454c74afd44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.jcp.org/jcr/nt/1.0resource> .
<http://127.0.0.1:8986/rest/test/4b/29/b6/01/4b29b601h/files/37b8c774-c4de-4257-abad-e454c74afd44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.jcp.org/jcr/mix/1.0mimeType> .
<http://127.0.0.1:8986/rest/test/4b/29/b6/01/4b29b601h/files/37b8c774-c4de-4257-abad-e454c74afd44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fedora.info/definitions/v4/repository#Binary> .
<http://127.0.0.1:8986/rest/test/4b/29/b6/01/4b29b601h/files/37b8c774-c4de-4257-abad-e454c74afd44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://pcdm.org/models#File> .
<http://127.0.0.1:8986/rest/test/4b/29/b6/01/4b29b601h/files/37b8c774-c4de-4257-abad-e454c74afd44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://fedora.info/definitions/v4/repository#Resource> .
<http://127.0.0.1:8986/rest/test/4b/29/b6/01/4b29b601h/files/37b8c774-c4de-4257-abad-e454c74afd44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://pcdm.org/use#OriginalFile> .
<http://127.0.0.1:8986/rest/test/4b/29/b6/01/4b29b601h/files/37b8c774-c4de-4257-abad-e454c74afd44> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.jcp.org/jcr/mix/1.0versionable> .
}
 WHERE { }
```
at http://127.0.0.1:8986/rest/test/4b/29/b6/01/4b29b601h/files/37b8c774-c4de-4257-abad-e454c74afd44/fcr:metadata

Caused by https://github.com/projecthydra/active_fedora/pull/1035

**Comment by jcoyne** [comment]
@escowles @tpendragon I think I've confirmed this:  Prior to this line https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/with_metadata/metadata_node.rb#L42 the metadata resource is readable, after that line it's in a corrupt state.

**Comment by escowles** [comment]
@jcoyne I'm taking a look at this now — I think you should be able to update the mime type, but since that's a recent change, a bug related to that wouldn't surprise me.

**Comment by tpendragon** [comment]
Running Plum's specs against this branch now, just to make sure we're not missing anything obvious

**Comment by tpendragon** [comment]
Plum's tests pass. @jcoyne?

**Pull request merged**
