### PR TITLE
fix advanced search ability issue

### PR DESCRIPTION
**Pull request by njaffer**
related to #555 . The current_user and ability is nil.

### CODE REVIEW

**Comment by jcoyne** [comment]
I don't think this is the right fix. Rather than handling a nil current_ability, current_abolity should never be allowed to be nil.

**Comment by jcoyne** [comment]
In other words, the fix we're looking for is to alter the controllers so that they pass the current_ability into the search builder.

**Comment by njaffer** [comment]
@jcoyne , I am looking at the code and when the HydraAccess is called from CatalogController#index, the @current_ability is not nil, but when it is called from AdvancedController#index, the @current_ability is nil

**Comment by jcoyne** [comment]
@njaffer that's right.  When you are done with this ticket, AdvancedController#index should pass the current_ability to the SearchBuilder and it will not be nil.

**Pull request closed without merging**
