### PR TITLE
Moving permissions note to separate partial for easier local customization

### PR DESCRIPTION
**Pull request by escowles**

### CODE REVIEW

**Comment by jcoyne** [comment]
:+1: Thanks for this.

**Comment by jcoyne** [comment]
You have offended the rubocop!

**Comment by escowles** [comment]
Dang, need to get in the habit of running `rake spec` instead of just `rspec` -- I've fixed it now.

**Comment by jcoyne** [comment]
@escowles did you push after fixing?

**Comment by escowles** [comment]
@jcoyne I pushed it to the wrong remote -- I just pushed it to my fork that this PR is from, and Travis is building it again now.

**Pull request merged**
