### PR TITLE
Remove unused styling

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by jcoyne** [comment]
@cbeer It appears to have exploded. :boom:

**Comment by mjgiarlo** [comment]
Restarted the build. Those were bizarre errors.

**Comment by mjgiarlo** [comment]
This build is officially haunted.

```
324 files inspected, no offenses detected
No config specified
rake aborted!
Errno::ENETUNREACH: Network is unreachable - connect(2) for "mirror.metrocast.net" port 80
/home/travis
```

:ghost:

**Comment by cbeer** [comment]
Sounds like the apache mirrors are having problems?

**Pull request merged**
