### PR TITLE
Remove custom color palette

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Restarted the build.

**Comment by mjgiarlo** [comment]
Restarting the build again. :angry:

**Comment by mjgiarlo** [comment]
Build died again. Not sure what I can do with this one, @cbeer.

**Comment by atz** [comment]
Build OK now?

**Comment by mjgiarlo** [comment]
Yep. Thanks, @atz

**Pull request merged**
