### PR TITLE
Use Rubocop to ensure consistently styled code

### PR DESCRIPTION
**Pull request by mjgiarlo**
This builds on the prior work done in Sufia, Hydra::PCDM, and Hydra::Works.

### CODE REVIEW

**Comment by cam156** [comment]
Looks like the failures are related to a routing change.

**Comment by tampakis** [comment]
Down to 8 failures

**Comment by mjgiarlo** [comment]
:clap: @cam156 @tampakis

**Comment by njaffer** [comment]
@tampakis I ran the test and I am getting 11 failures, while you were down to 8 , is the code updated? Here is the list of errors I got: https://gist.github.com/njaffer/4e228582b5d2dcf9dba8

**Comment by tampakis** [comment]
@njaffer, focus on those first 8, which are the ones failing on Travis. I think the last three are related to having to not having soffice installed and not having the citation concerns solrconfig.xml template loaded into jetty (maybe stopping jetty and running rake:jetty:config before restarting jetty will fix the last 2 for you?).

**Comment by njaffer** [comment]
Adding a line to rubocop.yml helped .. down to 3 errors.. which are I think related to my environment. Here is the gist link: https://gist.github.com/njaffer/4e228582b5d2dcf9dba8

**Comment by grosscol** [comment]
@mjgiarlo What are the "onlies" in the spec?

**Comment by tampakis** [comment]
@grosscol - @escowles removed them. His commit and mine got squashed

**Comment by mjgiarlo** [comment]
Hi, yes, sorry -- I started working on this again yesterday.  In so doing I squashed and rebased against master.

**Pull request merged**
