### PR TITLE
Implement File Manager UI

### PR DESCRIPTION
**Pull request by tpendragon**
Allows for reordering Works and assigning labels to them in one
interface.

### CODE REVIEW

**Comment by jcoyne** [comment]
Can you add a screenshot or two?  I'm curious as to why the specs are written in coffeescript and the code is written in ES6?

**Comment by tpendragon** [comment]
screen shot 2016-02-11 at 11 37 49 am
screen shot 2016-02-11 at 11 37 57 am
screen shot 2016-02-11 at 11 40 41 am

>  I'm curious as to why the specs are written in coffeescript and the code is written in ES6?
I've never been able to get Jasmine to run ES6...I didn't try that hard this time, though.

**Comment by tpendragon** [comment]
Alright, all in ES6 now.

**Comment by tpendragon** [comment]
The ES6 specs don't work in PhantomJS.

**Comment by jcoyne** [comment]
Can we hold off on merging this until #613 is fixed?

**Comment by tpendragon** [comment]
@jcoyne Sure? Is there a concern that this'll break a lot?

**Comment by jcoyne** [comment]
@tpendragon not really, but it's definitely a new feature vs a bug fix

**Comment by tpendragon** [comment]
> @tpendragon not really, but it's definitely a new feature vs a bug fix

Alright, sounds good, just ping me when it's time for me to rebase, if I end up needing to.

**Pull request merged**
