### PR TITLE
Extract lock functionality into module and use it to prevent race conditions in UploadSets

### LINKED ISSUE #560: Locking issues when uploading several files
_From @ojlyytinen on November 25, 2015 9:55_

Although this issue is similar to #1324, it is different in that it has nothing to do with uploading to a collection. The cause seems to be essentially trying to create the Batch object with the same ID twice when uploading several files. It appears that the code [Batch.safe_create](https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/batch.rb#L22-L29) doesn't sufficiently handle the race condition.

This doesn't happen every single time you upload several files but we ran into it twice in a fairly short timespan. Below are the two stack dumps from our logs. They are similar but not exactly the same. But it seems like the cause is still the same, the conflict is just detected at different points of execution.

```
E, [2015-11-24T15:13:53.480719 #17721] ERROR -- : GenericFilesController::create rescued Ldp::HttpError
	STATUS: 500 javax.jcr.ItemExistsException: A node definition that allows same name siblings could not be found for the node "{}42" in workspace "default"
	at org.modeshape.jcr.JcrSession$JcrPreSave.processAfterLocking(JcrSession.java:2422)
	at org.modeshape.jcr.cache.document.WritableSessionCache.runPreSaveAfterLocking(WritableSessionCache.java:541)
	at org.modeshape.jcr.cache.document.WritableSessionCache.save(WritableSessionCache.java:614)
	at org.modeshape.jcr.JcrSession.save(JcrSession.java:1166)
	at org.fcrepo.http.api.FedoraLdp.createOrReplaceObjectRdf(FedoraLdp.java:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java...
 /var/www/hydra/vendor/bundle/ruby/gems/ldp-0.4.1/lib/ldp/client/methods.rb:121:in `block in check_for_errors'
/var/www/hydra/vendor/bundle/ruby/gems/ldp-0.4.1/lib/ldp/client/methods.rb:119:in `tap'
/var/www/hydra/vendor/bundle/ruby/gems/ldp-0.4.1/lib/ldp/client/methods.rb:119:in `check_for_errors'
/var/www/hydra/vendor/bundle/ruby/gems/ldp-0.4.1/lib/ldp/client/methods.rb:98:in `block in put'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/notifications.rb:166:in `instrument'
/var/www/hydra/vendor/bundle/ruby/gems/ldp-0.4.1/lib/ldp/client/methods.rb:90:in `put'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/caching_connection.rb:24:in `put'
/var/www/hydra/vendor/bundle/ruby/gems/ldp-0.4.1/lib/ldp/resource.rb:72:in `create'
/var/www/hydra/vendor/bundle/ruby/gems/ldp-0.4.1/lib/ldp/resource/rdf_source.rb:21:in `create'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/persistence.rb:147:in `create_record'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/indexing.rb:53:in `create_record'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/callbacks.rb:237:in `block (2 levels) in create_record'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_save_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/callbacks.rb:237:in `block in create_record'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_create_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/callbacks.rb:236:in `create_record'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/persistence.rb:139:in `create_or_update'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/persistence.rb:27:in `save'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/validations.rb:50:in `save'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/persistence.rb:107:in `create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/sufia-models/app/models/batch.rb:23:in `safe_create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/sufia-models/app/models/batch.rb:15:in `rescue in find_or_create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/sufia-models/app/models/batch.rb:13:in `find_or_create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/app/controllers/concerns/sufia/files_controller_behavior.rb:236:in `process_file'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/app/controllers/concerns/sufia/files_controller_behavior.rb:105:in `create_from_upload'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/app/controllers/concerns/sufia/files_controller_behavior.rb:90:in `create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/app/controllers/concerns/sufia/files_controller/browse_everything.rb:9:in `create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/app/controllers/concerns/sufia/files_controller/local_ingest_behavior.rb:9:in `create'
/var/www/hydra/vendor/bundle/ruby/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/www/hydra/vendor/bundle/ruby/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'

...
```

```
E, [2015-11-24T15:17:26.404609 #7864] ERROR -- : GenericFilesController::create rescued RuntimeError
	Can't call create on an existing resource
 /var/www/hydra/vendor/bundle/ruby/gems/ldp-0.4.1/lib/ldp/resource.rb:70:in `create'
/var/www/hydra/vendor/bundle/ruby/gems/ldp-0.4.1/lib/ldp/resource/rdf_source.rb:21:in `create'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/persistence.rb:147:in `create_record'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/indexing.rb:53:in `create_record'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/callbacks.rb:237:in `block (2 levels) in create_record'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_save_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/callbacks.rb:237:in `block in create_record'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_create_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/callbacks.rb:236:in `create_record'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/persistence.rb:139:in `create_or_update'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/persistence.rb:27:in `save'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/validations.rb:50:in `save'
/var/www/hydra/vendor/bundle/ruby/gems/active-fedora-9.4.2/lib/active_fedora/persistence.rb:107:in `create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/sufia-models/app/models/batch.rb:23:in `safe_create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/sufia-models/app/models/batch.rb:15:in `rescue in find_or_create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/sufia-models/app/models/batch.rb:13:in `find_or_create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/app/controllers/concerns/sufia/files_controller_behavior.rb:236:in `process_file'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/app/controllers/concerns/sufia/files_controller_behavior.rb:105:in `create_from_upload'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/app/controllers/concerns/sufia/files_controller_behavior.rb:90:in `create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/app/controllers/concerns/sufia/files_controller/browse_everything.rb:9:in `create'
/var/www/hydra/vendor/bundle/ruby/bundler/gems/sufia-f8387043b826/app/controllers/concerns/sufia/files_controller/local_ingest_behavior.rb:9:in `create'
/var/www/hydra/vendor/bundle/ruby/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/www/hydra/vendor/bundle/ruby/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'

...
```

_Copied from original issue: projecthydra/sufia#1362_

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #560. (Heads-up, @ojlyytinen, and thanks for reporting this issue in Sufia.)

### CODE REVIEW

**Comment by grosscol** [comment]
From the issue #560, it looks like two workers try to find, can't find the time, so they both create and one wins.  This prevents multiple calls to create.  What happens to the thread that doesn't find and can't create?  Does that file upload fail?

**Comment by mjgiarlo** [comment]
@grosscol The second thread waits on a lock. By default it'll wait up to 2 minutes, trying to acquire a lock at intervals up to 200ms. If it still can't get a lock after those 2 minutes, it raises `UnableToAcquireLockError`.
​
https://github.com/projecthydra-labs/curation_concerns/blob/55686dce552c39ec9423ac055961f90ae6321cea/curation_concerns-models/lib/curation_concerns/configuration.rb#L90-L110

**Comment by ojlyytinen** [comment]
Shouldn't safe_create still have ```rescue ActiveFedora::IllegalOperation``` inside the lock? As it stands, if you have two threads trying to create at the same time then only one of them will succeed and the other one will raise an error because the UploadSet already exists.

```ruby
def safe_create(id)
  acquire_lock_for(id) do
    begin
      UploadSet.create(id: id)
    rescue ActiveFedora::IllegalOperation
      UploadSet.find(id)
    end
  end
end
```

**Comment by jcoyne** [comment]
Because of the lock you could not have two processes running the block simultaneously.

**Comment by mjgiarlo** [comment]
@grosscol @ojlyytinen @jcoyne The lock prevents two processes from running the block simultaneously, yes. The potential error condition unaccounted for in this PR is: what happens when two processes enter `#safe_create` at the same time with the same identifier? One gets the lock and will create an UploadSet with its id. And the other will wait to acquire a lock and then try to create an UploadSet with the same id. Is that the error condition that this PR needs to handle now?

**Comment by ojlyytinen** [comment]
It'll still be a problem if the lock is ran twice with the same id, even it doesn't happen concurrently. You'll get an error because the FileSet already exists for the second thread. And assuming file uploads still work similarly to how they are in Sufia 6, it's fairly likely that you'll have several http requests arrive very close to each other which all try to create a FileSet with the same id. If two such requests get to safe_create then one of them will fail, meaning that the upload will fail.

It's of course a matter of opinion how you want to organise the code and where you want to put the lock but in the end #find_or_create should either find an existing object or create a new one and do all this in a thread-safe manner. Otherwise uploads are going to fail. Just simply putting the lock in #find_or_create and getting rid of #safe_create should work.

**Comment by tpendragon** [comment]
@ojlyytinen is right. You need something like first_or_create.

**Comment by mjgiarlo** [comment]
@ojlyytinen @tpendragon @jcoyne See the latest change. I am rescuing three exceptions on calls to `#find` within `acquire_lock_for`:

 * `ActiveFedora::ObjectNotFoundError`, for when the UploadSet has not yet been created
 * `ActiveFedora::ActiveFedoraError`, for when the UploadSet tries to find an identifier that already belongs to an AF object with a different model (for instance, a FileSet)
 * `Ldp::Gone`, for when the UploadSet tries to find an identifier that belongs to an AF object that has been destroyed

Before I go further, I'd like feedback on the above. Should I check for those three error conditions? If so, I need to add some tests and resubmit. If not, I can scale that back and resubmit. Either way this PR is probably not mergeable and needs a little more work, but I want to choose my own adventure wisely so pls do advise!

**Comment by ojlyytinen** [comment]
If you get Ldp::Gone or ActiveFedora::ActiveFedoraError then UpdateSet.create is going to fail as well won't it? It's going to try the same identifier and it won't work. I don't think there's really any sensible way to recover from those two errors so probably best to just let them through.

**Comment by mjgiarlo** [comment]
@ojlyytinen Er, derp. Yes. Is it Friday yet?

**Comment by mjgiarlo** [comment]
Build is passing and we're now locking `#find_or_create`.

Are we OK with continue to stub out locks in Travis (because Redis isn't running), or should we bite the bullet and add redis to `.travis.yml` so that we can be sure our locking is tested automatically? Looking at @tpendragon @jcoyne @escowles in particular on this one.

**Comment by tpendragon** [comment]
> we can be sure our locking is tested automatically

I'm not sure. I'm inclined to trust redlock, as long as our locker has unit tests to make sure it calls it, that should be fine.

**Comment by ojlyytinen** [comment]
Locking looks good to me.

**Comment by mjgiarlo** [comment]
Thanks, y'all. Sounds like it's ready to merge?

**Pull request merged**
