### PR TITLE
Update HydraWorks dependency

### PR DESCRIPTION
**Pull request by grosscol**
Update hydra works dependency

### CODE REVIEW

**Comment by jcoyne** [comment]
The Rakefile is requiring 'jettywrapper', but it's not declared as a dependency.

**Comment by jcoyne** [comment]
This branch needs a rebase

**Comment by jcoyne** [comment]
I don't understand why you pulled my commit onto this branch. Can you rebase?

**Comment by grosscol** [comment]
Rebased, but fix for error depends on #608

**Comment by jcoyne** [comment]
@grosscol This branch still has my commit. Can you rebase -i and remove it?

**Comment by jcoyne** [comment]
@grosscol #608 is merged, please rebase this.

**Comment by grosscol** [comment]
Rebasified.  Even passes tests.

**Pull request merged**
