### PR TITLE
Return a single value rather than an array. 

### LINKED ISSUE #449: Mime-type is being returned as an array
The current version of SolrDocumentBehavior returns an array (rather an a single value) for the mime type https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/solr_document_behavior.rb#L115:

```
    def mime_type
      self[Solrizer.solr_name('mime_type', :stored_sortable)]
    end
```

This causes several methods in HydraWorks to work incorrectly. For example method to detect if a mime type is an office document here https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/models/concerns/file_set/mime_types.rb#L22 expects `mime_type` to be a single string like `"text/rtf"` rather than `["text/rtf"]`

I think we should update the code in Curation Concerns to return a single value rather than an array to preserve the semantics that this method used to provide. Otherwise we will need to update everyplace where mime_type is accessed.

### PR DESCRIPTION
**Pull request by hectorcorrea**
Fixes #449

### CODE REVIEW

**Comment by jcoyne** [comment]
How is it that a stored sortable (singular) is ever an array?

**Comment by jcoyne** [comment]
Should this have a test?

**Comment by hectorcorrea** [comment]
@jcoyne I can add a test.

As far as the stored_sortable, I left that as it was (which is a change on how Sufia used to store it.) I could change that as well but I wasn't sure about this. Thoughts?

**Comment by jcoyne** [comment]
I would think that solr returns _ssi fields as singular, so that casting to array and taking the first element would be unnecessary.

**Comment by hectorcorrea** [comment]
Nevermind.

**Pull request closed without merging**
