### PR TITLE
Make the views rely on local variables instead of ivars

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by escowles** [comment]
What's the motivation for this change?  I see it simplifies the test a bit, but is there some other reason?

**Comment by awead** [comment]
:+1: after rebase

**Comment by awead** [comment]
@escowles it's kind of a preference, but using local variables allows you to override the view more easily.

**Comment by jcoyne** [comment]
@escowles another reason for this change was to align the partials so they are all using the same local variable: https://github.com/projecthydra-labs/curation_concerns/blob/master/app/views/curation_concerns/base/show.html.erb#L9-L13

**Comment by escowles** [comment]
@awead @jcoyne Thanks, those both sound like good things to make it easier for downstream customization of the views.  So I'm also :+1: after rebasing.

**Pull request merged**
