### PR TITLE
use hydra works jetty tasks for full text config

### LINKED ISSUE #279: jetty config task runs hydra-works jetty config rake task
Make the 'curation_concerns:jetty:config' rake task call the (new) hydra-works jetty config rake task that's being added for projecthydra-labs/hydra-works#201

This is necessary because we moved text extraction (which relies on solr's text extraction service) down into hydra-works.

### PR DESCRIPTION
**Pull request by tampakis**
Closes #279.

Blocked by https://github.com/projecthydra-labs/hydra-works/pull/204. Gemfile.extra currently refs the unmerged Hydra-Works branch.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
https://github.com/projecthydra-labs/hydra-works/pull/204 has been merged. Do you want to rejigger this PR before it's merged, @tampakis?

**Comment by tampakis** [comment]
@mjgiarlo I did after the merge. Thanks for following up.

**Comment by tampakis** [comment]
@mjgiarlo it's good to go!

**Comment by mjgiarlo** [comment]
:boom:

**Pull request merged**
